jonathanpeppers/inclusive-code-reviews-browser

src-packed/suggestions.js, test/suggestions.js
Context: https://stackoverflow.com/a/2232947/132442
Fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/16
=> Fix suggestions to only report for "whole words"

src-packed/validator.js, src/config/config.js, test/validator.js
Add a suggestion when a comment is too brief
fixes #28
=> Add check for brief comment

src-packed/appinsights.js, src/background/extension-main.js, src/common/messages.js, src/content/ltAssistant.js, src/content/toolbar.js
This still seems to break some of the data, still a WIP.
=> [appinsights] send all data only from the background extension

src-packed/suggestions.js
Suggestions for one of the terms were combined; splitting them into multiple suggestions.
=> Split suggestions

README.md, src-packed/textAnalytics.js, src-packed/validator.js, test/textAnalytics.js, test/validator.js
Context: https://docs.github.com/en/actions/security-guides/encrypted-secrets
The secrets will be blank on PRs from forks.
Let's just set it up so the tests are runnable & they skip when values are blank.
=> [tests] allow PRs from forks

src-packed/suggestions.js
Example phrase:
While I agree with this whitespace change, it does make the PR bigger to review than necessary.
New version:
While I agree with this formatting change, it does make the PR bigger to review than necessary.
=> Add 'formatting' as an alternative for 'whitespace'.

src-packed/suggestions.js, test/suggestions.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/70
Find and iterate through all instances of words that have a suggested
replacement.
=> Match all instances of words with suggestions

package-lock.json, package.json, src-packed/appinsights.js, src/manifest.json
Apparently this is in four files???
=> Bump to version 0.1.1

src-packed/textAnalytics.js, test/textAnalytics.js
Context: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter
The built-in `Intl.Segmenter` seems to work reasonably well for splitting large blocks of text into sentences.
I had to adjust a couple tests, as the sentence splitting is slightly different than Azure Text Analytics was doing before.
=> Add rudimentary "sentence splitting"

README.md
This PR is ready for review! All tests are passing. Let me know if you have any feedback.
=> Add edge to README

src-packed/suggestions.js
For your review: based on some documentation from universities and other tech companies, I added some suggested words to be replaced. #60
=> Added words for replacement and included reference

_import.js, src-packed/appinsights.js, src-packed/validator.js, src/background/extension-main.js, src/background/validator.js
Trying to slowly port changes from `manifest-v3` to `main`.
This might help identify a few things that aren't working yet in `manifest-v3`.
=> Use `globalThis` over `window` where appropriate

src/common/extensionEnvironmentAdapter.js, src/common/extensioni18nManager.js, src/common/tweaksManager.js, src/content/ltAssistant.js, src/popup/popup.js
=> `browser.i18n` -> `chrome.i18n`

.github/workflows/main.yml, package-lock.json, package.json, test/openai.js
This is just a test for now, using my API key from Azure.
We'll probably need to tweak this, so it can work with both regular OpenAI and Azure OpenAI.
=> Add example using Azure OpenAI

src-packed/openaiClientFactory.js, test/openaiClientFactoryTest.js
Dependabot bumps broke everything
=> [openai] changes to use latest npm module

package-lock.json, package.json
Context: https://www.npmjs.com/package/chrome-types
Context: https://github.com/jonathanpeppers/HelloChrome
Playing around with a "hello world" extension, I found installing this package gives you intellisense about Chrome APIs. Love it!
=> [npm] install chrome-types

src/background/extension-main.js, src/config/config.js, src/manifest.json
Should not actually be needed.
=> Remove `alarms` permission

src/content/errorCard.js
Just something really simple for now, so you can't click twice.
=> Add "Loading..." indicator

PRIVACY.md, src/background/extension-main.js, src/common/environmentAdapter.js, src/common/extensionEnvironmentAdapter.js, src/popup/popup.css, src/popup/popup.html, src/popup/popup.js
Context: https://github.com/ArthurGareginyan/privacy-policy-template
Also cleaned up the `openFeedbackForm()` code.
=> Add a basic "privacy policy" to the extension

.github/workflows/main.yml
=> [build] remove `openai_key`

test/openaiClientTest.js
Add example to use the new comment rewrite API
=> Add example to use the new comment rewrite API

src-packed/validator.js, test/validator.js
We may wait to merge this next week.
=> [validator.js] switch to `CommentRewrite` endpoint

src-packed/textAnalytics.js, test/textAnalytics.js
Also replace case-insensitively.
Contributes towards https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/309.
=> Replace all occurrences of .NET instead of just the first one.

test/openaiClientTest.js
To see if more reliably green.
=> [tests] comment out a few openai api tests

package-lock.json, package.json
There is a dependabot security alert on this.
=> [npm] require braces 3.0.3
