jonathanpeppers/inclusive-code-reviews-browser

src-packed/appinsights.js, src/content/dialog.js, src/content/errorCard.js, src/content/ltAssistant.js, src/content/toolbar.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/14
* We now have page views for dialog opening
* Removed the 'disable this rule everywhere' option
* Send event for 'ignoreSuggestion'
* Send event for 'appliedSuggestion' and include total the extension has recorded
=> Adjust tracking/analytics behavior

docs/telemetry.md, src-packed/validator.js, src/background/extension-main.js, src/background/validator.js, src/common/messages.js, src/content/ltAssistant.js, test/validator.js
Implements https://github.com/jonathanpeppers/inclusive-code-comments/issues/24
I implemented the bulk of the logic for this in
`src-packed/validator.js`. A `hasFoundSuggestionsBefore` variable
tracks the state -- and we report `manualFix` when a fix is resolved
after a previous one was found. Doing it this way, I was able to write
tests and test the interaction between the `appliedSuggestion` event.
The only problem I found was the way `ltAssistant.js` sent the
`appliedSuggestion` event from *inside* web pages, instead of from the
extension in the background. So we ended up with two instances of
`src-packed/validator.js` and we get two events: `appliedSuggestion`
then `manualFix`!
To solve this, I use `sendMessage()` to send from the page:
browser.runtime.sendMessage({ command: …
=> Add a 'manualFix' custom event

src/options/options.html
Hide rules and personal dictionary, I m not removing these as we see that they could help us in the future.
- personal dictionary for words we want flagged
- rules related with how we analyse the text 
Fixes #21
=> Hide extra settings that we can use in the future

.github/workflows/main.yml, README.md, package-lock.json
Something updated node.js on my machine.
`npx xt-build` was failing with:
'packed.js' errored after 1.04 s
[11:00:07] Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:67:19)
at Object.createHash (node:crypto:130:10)
at module.exports (C:\src\inclusive-online-comments\node_modules\webpack\lib\util\createHash.js:135:53)
at NormalModule._initBuildHash (C:\src\inclusive-online-comments\node_modules\webpack\lib\NormalModule.js:417:16)
at handleParseError (C:\src\inclusive-online-comments\node_modules\webpack\lib\NormalModule.js:471:10)
at C:\src\inclusive-online-comments\node_modules\webpack\lib\NormalModule.js:503:5
at C:\src\inclusive-online-comments\node_modules\webpack\lib\NormalModule.js:358:12
at …
=> Run 'npm update'

src-packed/suggestions.js, test/suggestions.js
If the text to replace is capitalized, the suggestions should also be capitalized!
Also, the suggestions should not be duplicated and should be the same regardless of casing.
Fixes #31 
Screenshot example:
=> Remove case sensitivity - match casing of suggestions

src-packed/validator.js, test/validator.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/48
This was doing `length: text.length - 1`, which didn't seem to be right.
Removing the `-1` fixed the issue, and I updated a test for this.
=> Fix "comment too brief" off by one error

src-packed/textAnalytics.js, test/textAnalytics.js
Skip code blocks (both fenced and indented) when analyzing text.
This is done by replacing code blocks with spaces before sending text off to
be analyzed (this way analyzed text has the same location information as the
input).
Fixes https://github.com/jonathanpeppers/inclusive-code-comments/issues/52.
=> Skip code blocks when analyzing text. Fixes #52.

assets/locales/en/messages.json, src/content/dialog.js, src/content/toolbar.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/12
The toolbar and dialog have been updated to display "render failure" or
"exception" styled icons and text when user input exceeds 10,000 chars.
This replaces the previously used "upgrade" styled icons and branding.
=> Improve messaging when comment text is too long

src-packed/suggestions.js
Context #46
The Text Analysis service does not seem to pick up some regional
phrases which are negative. To work around this for now lets start adding
additional negative sentiments to the suggestions.js.
We do not need to provide replacement suggestions, we can leave them empty
and the extension will flag them as negative as usual.
=> Add custom negative sentiments to suggestions.js

src-packed/validator.js, test/validator.js
After looking at #57, the number of `manualFix` events seemed low.
It looked like we only reported this event when there was an error in
the past, and now all errors are fixed. Change this value to an
integer of the number of errors, and we can report `manualFix` if the
number of errors *goes down*.
This way we'll get the `manualFix` event if you have more than one
error and fix at least one.
=> [telemetry] better logic for the 'manualFix' event

.github/workflows/main.yml
Fixes: #66
Replaces: #72
Attempt to work around the [zipped artifact download limitation][0] by
uploading unzipped content.
[0]: https://github.com/actions/upload-artifact#zipped-artifact-downloads
=> [ci] Unzip extension before uploading

src-packed/textAnalytics.js, test/textAnalytics.js
Partially fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/47
Replaces: https://github.com/jonathanpeppers/inclusive-code-comments/pull/71
Adds support for ignoring certain words or phrases with a negative
sentiment.  These ignorable words will be replaced with an empty string
of equal length in the comment before sending it to the Text Analytics
service.
Only a couple of phrases have been added to this list, and it can be
expanded in the future as needed.
=> Add ignore list for certain negative phrases

src-packed/textAnalytics.js, test/textAnalytics.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/62
Skip image tags when analyzing text.
This is done by replacing the image url with spaces before sending text off to be analyzed (this way analyzed text has the same location information as the input).
Only the image url is removed, the alt text is kept. I'm also adding at the beginning and end of image tags, so that previous sentences, the alt text, and the next sentence are all actually considered separate sentences.
=> Skip image tags when analyzing text.

src-packed/suggestions.js, src-packed/textAnalytics.js
Fixes #46
This is an update to #59 which adds some more negative intent words.
It also adds the work negative to the ignore list, since that word
will probably be used for PR's to describe mathematical code.
=> Add some more Slang works which have negative intent.

src-packed/suggestions.js
-  "wild" portrays the magnitude of disbelief that is usually associated with "crazy". This also seems to have backing based on suggestions [here](https://www.huffpost.com/entry/disability-language-work_l_5f85d522c5b681f7da1c3839).
=> Add "wild" to the list of alternate words to "crazy"

src-packed/textAnalytics.js, test/textAnalytics.js
It appears that backticks (`) and single quotes (') add negative sentiment to the text analyzer.
I can't really think of any good reason that this should be the case and it seems that the analyzer does not penalyze the use of double quotes (") - at least not a noticable amount to make the sentence go over the threshold.
Therefore, I thought replacing the backticks and single quotes to double quotes would be a good solution.
Another option is that we could even just remove the backticks and single quotes for the analyzer!
We should keep in mind that single quotes are used in contractions.
Addresses this issue: https://github.com/jonathanpeppers/inclusive-code-comments/issues/92
=> Change backticks and single quotes to double quotes

src-packed/validator.js
Context: https://github.com/jonathanpeppers/inclusive-code-comments/pull/97#pullrequestreview-900455441
To address a specific case where we saw text like:
`yield`
negative 87%
Changed to:
"yield"
negative 62%
Let's increase the threshold to 90% and see if things are less noisy?
=> Increase negative sentiment from 75% to 90% confidence

test/textAnalytics.js
It seems that Azure Text Analytics must have rolled out a change that affects where they separate pieces of text into discrete sentences.
Overall the test changes seem "better" maybe a little cleaner actually?
=> [tests] fixes for Azure Text Analytics behavior changes

src-packed/validator.js, test/validator.js
Implements #77
Still need to look more into some of the logic with brief phrases - single words don't get flagged, and short phrases followed by certain punctuation markers do (i.e. ">" as in https://github.com/jonathanpeppers/inclusive-code-comments/issues/77#issuecomment-1036339032)
=> Add logic to ignore certain brief phrases

src-packed/suggestions.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-comments/issues/82
Issue #82 appears to be Azure Text Analytics sentiment analysis, but
as a way to address this. We should recommend using "stop" or "cancel"
in favor of "kill".
I tested "killing it", and it appears things are working as intended
when one problematic phrase includes another inside of it. "kill" is a
substring of "killing it", but it appears to work fine.
=> Add suggestions for "kill", and "stuck"

assets/locales/en/messages.json, src/common/tweaksManager.js
Fixes #110
Note that it doesn't seem to actually _work_ on the Edge Extensions site at XYZ. But now it doesn't warn, either.
See in screenshot there is no more warning:
But, also, it doesn't light up the extension either:
So, really this PR just removes what appears to be an innocuous warning.
=> Remove warning when running on Edge Extensions web site

package-lock.json
`npx` was warning me:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Afterward, it updated `caniuse-lite`.
=> Run `npx browserslist@latest --update-db`

src-packed/textAnalytics.js, test/textAnalytics.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/133
Context: https://stackoverflow.com/a/30281147/183422
Doing this because the data we trained the model against has all GitHub handles removed for privacy reasons. It also helps accuracy, as we don't want folks' GitHub handles to have an effect on the "sentiment" of comments.
=> Replace GitHub handles with @github

src-packed/textAnalytics.js, test/textAnalytics.js
Context: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/132
Future work will need to be done on the ML side:
* Replace the same way when loading/saving `.csv` files
* Replace our existing data & update the model
* Document this replacement
=> Replace `inline code blocks` with #code

src-packed/textAnalytics.js, test/textAnalytics.js
Context: https://github.com/jonathanpeppers/inclusive-code-reviews-ml/pull/57
Context: https://github.com/jonathanpeppers/inclusive-code-reviews-ml/issues/48
Allows things like:
This is a ```code block```
=> Update regex to allow triple backtick code blocks

src-packed/textAnalytics.js, test/textAnalytics.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/123
We've found that adding a `.`, `:`, etc. can influence the results of the machine learning model. Let's trim out trailing punctuation to solve this.
Future changes need to happen in the ML model side: remove trailing punctuation from the dataset, etc.
=> Trim trailing punctuation

src-packed/textAnalytics.js, test/textAnalytics.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/140
This should hopefully improve reliability around URLs inline in comments.
Future changes will be needed on the ML side.
=> Replace URLs with `#url`

src-packed/validator.js, src/config/config.js, test/validator.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/119
This allows phrases like "Thank you" now.
=> Change MIN_REVIEW_LENGTH 15 -> 9

src-packed/suggestions.js, test/suggestions.js
This PR is adding a category of common wording pattern that might be able to change to be soften. 
"should just" is a very common saying in my native language. I get feedback from native Enlish speaker that it can be soften by changing to "can probably". e.g. "We should just delete this section" -> "We can probably delete this section".
=> Common wording pattern that can be soften

src-packed/validator.js, test/validator.js
This PR addresses the PR Change ordering of negative sentiment vs "too brief" #153
Moving the order of checking negative sentiment before the check if the comment is too short.
Also fixes a small typo in the message if the comment is too brief.
Draft since it could still probably use a test
=> Fix Change ordering of negative sentiment vs "too brief" #153

src-packed/suggestions.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/172
We can always bring this back if we change our mind.
We got this response from an internal Microsoft email:
> However, after further research and discussion, we are not currently
> planning to publish guidance recommending against the use of the
> word "native." In its broader definition, the word is used as an
> adjective or a noun to describe innate characteristics or traits
> present from inception. This has been applied to people born in many
> different geographical regions, not exclusively to people of a
> certain identity. This use is not inherently derogatory or
> appropriative in any way, nor does it exclude any group or groups of
> persons (everyone can be "native" to a different area). In fact, …
=> Don't suggest "native" -> "unmanaged"

src-packed/suggestions.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/178
Common phrases are:
* "hit OK" -> "click OK"
* "hit OK" -> "tap OK"
* "customers hit this problem" -> "customers run into this problem"
=> Other suggestions for "hit"

docs/telemetry.md, src-packed/appinsights.js, test/appinsights.js
Adding the Azure ADO org to the AppInsights telemetry allowed list.
Verification
=> Include page view telemetry for Azure ADO

src-packed/suggestions.js
ChatGPT says:
> Me: What is a more inclusive term than "whitespace"? Referring to
> space or tab characters in programming languages or text files.
> ChatGPT: "Horizontal spacing" or "indentation" are more inclusive
> terms that can be used instead of "whitespace" when referring to
> space or tab characters in programming languages or text files. The
> term "whitespace" has a historical association with the idea that
> spaces are "white" and can be considered offensive. Using more
> neutral terms such as "horizontal spacing" or "indentation" can
> avoid any potential offense and make the conversation more
> inclusive.
=> Add suggestions for "whitespace"

package.json, src-packed/validator.js
Context: https://github.com/microsoft/onnxruntime/issues/14445
When moving to Chrome V3, we hit the error:
TypeError: URL.createObjectURL is not a function
at Object.locateFile (packed.js:formatted:18165:126)
at O (packed.js:formatted:345:61)
at Object.ib (packed.js:formatted:718:49)
at Object.mb (packed.js:formatted:722:73)
at fe (packed.js:formatted:594:48)
at Te (packed.js:formatted:807:42)
at ort-wasm-simd-threaded.wasm:0x772d56
at ort-wasm-simd-threaded.wasm:0xeb64e
at ort-wasm-simd-threaded.wasm:0x1c4048
at ort-wasm-simd-threaded.wasm:0xe5575
It appears we can set `numThreads` to 1 to avoid this code path.
There appear to be different `.wasm` files:
Uncompressed Compressed
8667133      2411351  ort-wasm-simd-threaded.wasm
8719890      2413744  ort-wasm-simd.wasm
7908412      2248465 …
=> Set `ort.env.wasm.numThreads = 1`

src/content/gdocs/injector.js, src/content/gdocs/script.js, src/content/styles/styles.css, src/manifest.json
It appears the latest extension doesn't work in current Google docs anyway. Google probably makes this a "moving target", and their latest changes probably broke this extension.
Remove JavaScript code and CSS related to Google docs, to help with Chrome V3 effort.
=> Remove code related to Google docs

src/background/extension-main.js, src/common/messages.js, src/config/config.js, src/content/ltAssistant.js, src/content/offscreen.html, src/content/offscreen.js, src/manifest.json
Context: https://stackoverflow.com/a/66618269
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/209
Instead of sending the `CHECK_HEALTH` message in web pages where our
extension is running...
Create an `offscreen` page that is always loaded. It can do this work
instead -- and can keep the service worker alive indefinitely.
=> Create "offscreen" page to keep service worker alive

test/openai.js
- The open ai response can change even for the same input. This would be breaking the tests if we have strict equal check.
- expanding test timeout
=> Improve chat unit test stability

test/openai.js
If someone runs the tests locally without setting up `secrets.js` or they open a PR from a fork -- all the openai tests would fail because the API key is missing.
Let's just skip those tests and write to the console if this happens.
=> [tests] skip openai tests on PRs from forks

src-packed/textAnalytics.js, src-packed/validator.js, test/textAnalytics.js, test/validator.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/238
This fixes cases like:
This is bad. This is good.
Where it used to underline the blank space after "This is bad. ".
Now it stops the underline at the `.`.
=> Ignore trailing whitespace for length underlined

src/background.js
Context: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/pull/285
This is a smaller patch that also seems to fix the general problem here that exists for the Chrome V3 extension (on Chrome store):
1. Extension is working.
2. At some point Chrome "stops" the background service worker.
3. Extension no longer works until you click the "Restart" button in the edge://extensions page.
One problem here was we loaded all the scripts in `self.oninstall`, where we could just load them directly instead. This was basically only making the extension work for a period of time after it was initially installed.
You can test this behavior with the "Stop" button on this page:
edge://serviceworker-internals/?devtools
=> Allow V3 extension to "wake up" appropriately

package-lock.json, package.json, test/openaiClientTest.js, test/validator.js
Add `@type` packages to get better intellisense in VSCode:
* chrome, mocha, chai
Update mocha and chai directly, these are transitive dependencies of `extension-cli`.
Add a "retry" to the tests that have a timeout and rely on OpenAI responses. A single retry should hopefully solve random test failures.
=> [npm] packages to improve dev experience

src-packed/validator.js
FrequencyPenalty helps safeguard against the model repeating itself. By setting the value to 1.0 in its available range of -2.0 to 2.0, we can help minimize repetition while also maintaining the quality of responses returned.
Refs: 
- https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.chatcompletionsoptions.frequencypenalty?view=azure-dotnet-preview
- https://platform.openai.com/docs/guides/text-generation/parameter-details
=> Adjust FrequencyPenalty hyperparameter

package-lock.json, package.json
I think we should be using `@types/chrome` instead here.
=> [npm] remove `chrome-types`

src-packed/validator.js
I think this would happen if the first call to send telemetry was the "Ask an AI" button:
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'trackEvent')
at packed.js:1:719591
at BackgroundApp._onAskAnAIMessage (extension-main.js:405:27)
at BackgroundApp._onMessage (extension-main.js:242:25)
I changed everything to do:
--appinsights.trackEvent('askAI');
++getAppInsights().trackEvent('askAI');
So they all check if `appinsights` is null.
=> Fix error with `appinsights`

src/manifest.json
I tried to submit our first Chrome V3 version of this extension to the Edge store and it says:
Your package failed certification. Make corrections and certify again.
The following checks failed:
Package acceptance validation error:
The manifest shouldn't contain update_url field.
Error code: update_url: https://clients2.google.com/service/update2/crx Line: 55 Column: 66
Removing this line from `manifest.json` to try again.
=> [manifest] remove `update_url` for Edge

src-packed/suggestions.js
I noticed the extension underlines "hang", but not "hangs".
=> [suggestions] hangs -> freezes

docs/telemetry.md, src-packed/validator.js, src/content/ltAssistant.js
This change adds telemetry for when the user requests the various suggestion popups, such as the inline error card or the corner indicator dialog.
This telemetry will show how the user is getting suggestions - if at all.
Fixes #328
=> Add telemetry to track suggestion popups

package-lock.json, package.json, src-packed/textAnalytics.js, test/textAnalytics.js
Fixes the error:
1) textAnalytics
Negative:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/inclusive-code-reviews-browser/inclusive-code-reviews-browser/test/textAnalytics.js)
It appears that the onnxruntime is slow on the first call.
I added a method to explicitly initialize and made this the first test with a timeout.
=> [tests] fix failing CI: `textAnalytics.js Negative`

src/content/errorCard.js
Context: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/312
There is some useless info the extension puts on GitHub issues.
This came from the original spellchecker source code, so just removing it.
=> [report] remove weird information at the bottom

assets/locales/en/messages.json, src/content/styles/styles.css, src/content/toolbar.js
We generally click on the underlined word in text, but there is a "second popup" that is not fully functional and a bit odd:
* It shows negative sentiment with text strikethrough, which is confusing.
* It has options to change language?!?
* It has options to dock the popup all over the web page.
There are also a couple issues opened, related:
* https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/338
* https://github.com/jonathanpeppers/inclusive-code-reviews-browser/pull/329
For now, let's just disable the second popup? I also disabled the hover effect for the pointer and updated the tooltip text for this button.
=> Disable clicking the second popup

src-packed/validator.js, test/validator.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/320
=> Don't flag `/rebase` as "too short"

src-packed/suggestions.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/371
Just looking up the synonyms for "execution":
* noun as in *killing*
Made me think this is a good one to keep!
* noun as in *carrying out of a task*
I added more examples for `execution`, which could be commonly used in programming.
=> Suggestions for "execute" and "execution"

src-packed/appinsights.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/405
Store an anonymous `self.crypto.randomUUID()` value, we can use to just find out "unique installs" of the browser extension.
This used to work automatically by AppInsights, but it either broke when we moved to Chrome V3 or a dependabot update.
With this change I see in the network tab:
ai.user.id : "ab57ffa4-f33f-46ee-b4fc-94da8fb6c5c5"
I see the same number throughout the session, and it's different if I uninstall and reinstall the extension.
=> [telemetry] add `ai.user.id` to identify unique installs

src-packed/appinsights.js, src-packed/validator.js
So we can correlate requests for this service on the backend if needed.
=> [telemetry] pass appinsights user to CommentRewrite API

src/content/ltAssistant.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/180
I found a method named `_disableOtherSpellCheckers` that sets `spellcheck="false"` on `<textarea/>` elements. I just removed it and the test case:
This is so dubm!
This shows a spellcheck squiggle *and* our squiggle now.
=> Restore spellchecking for `textarea`'s

src/background/extension-main.js, src/config/config.js
The upstream browser extension has a feature to load configuration from remote server. For ICR extension, this remote configuration server does not apply anymore. So, this PR is removing the remote configuration load part.
#Remove configuration server
https://languagetool.org/webextension_config.json
=> remove external configuration load

src-packed/validator.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/429
I think that gives a less of a "warning" vibe, as we are just suggesting better options.
=> All underlines are purple now

src/background/extension-main.js
Fixes: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/issues/314
Error in event handler: TypeError: Cannot destructure property 'geoIpLanguages' of 'this._storageController.getSettings(...)' as it is undefined. at BackgroundApp._getPreferredLanguages (chrome-extension://plmhdfocagbmlgnabhleebabidkfikfj/background/extension-main.js:337:33) at BackgroundApp._onValidateTextMessage (chrome-extension://plmhdfocagbmlgnabhleebabidkfikfj/background/extension-main.js:347:24) at BackgroundApp._onMessage (chrome-extension://plmhdfocagbmlgnabhleebabidkfikfj/background/extension-main.js:232:25)
=> Null check if getSettings() returns null
